<div class="buttonsocial">
    <a href="#" class="fly-button" id="facebook-button" target="_blank">Facebook</a>
</div>
<div class="span4 restaurants_block_right">
    <ul  class="nav nav-stacked" id="restaurants_block_right"></ul>
</div>
</div>
<div class="buttonsocial">
    <a href="#" class="fly-button" id="app-store-button" target="_blank">App Store</a>
</div>

<div class="buttonsocial">
    <a href="#" class="fly-button" id="google-paly-button" target="_blank">Google Play</a>
</div>

<div class="buttonsocial">
    <a href="#" class="fly-button" id="facebook-button" target="_blank">Facebook</a>
</div>

<div class="buttonsocial">
    <a href="#" class="fly-button" id="vkontakte-button" target="_blank">Vkontakte</a>
</div>

<div class="buttonsocial">
    <a href="#" class="fly-button" id="twitter-button" target="_blank">Twitter</a>
</div>

<div class="buttonsocial">
    <a href="#" class="fly-button" id="registration-button" target="_blank">Registration</a>
</div>

<div class="buttonsocial">
    <a href="<?php echo $this->url('zfcuser/login');?>" class="fly-button" id="login-button" target="_blank">Login</a>
</div>