


<?php echo $topview; ?>
<?php echo $navigation; ?>


<div class="row-fluid">
    <div class="span3 fitness_category">
        <?php echo $this->category; ?>
    </div>
    <div class="span7">
        <div class="fitness_grid">
            <h3>Салоны города Ялты</h3>
            <ul class="grid_attraction cs-style-2">
                <?php foreach($salons as $salon) :?>
                    <li>
                        <figure>
                            <img width="100" height="100" class="main-image" src="<?php echo $this->basePath() . substr($salon->salon_main_photo,7);?>"/>
                            <figcaption>
                                <a href="<?php echo $this->url('zfcadmin/salons',
                                    array('action'=>'zfcadmin/salons', 'salon_id_name' => $salon->salon_id_name));?>"><?php echo $this->escapeHtml($salon->salon_name); ?></a><br/>
                                     <span><b>Адресc:</b>   <span><?php echo $this->escapeHtml($salon->salon_address); ?></span>
                                     <span><b>Режим работы:</b>   <span><?php echo $this->escapeHtml($salon->salon_time_work); ?></span>
                                     <span><b>Стоимость билета:</b>   <span><?php echo $this->escapeHtml($salon->salon_ticket_price); ?></span>
                                     <span><b>Описание:</b>   <span><?php echo $this->escapeHtml($salon->salon_type); ?></span>


                                        <button class="button button-attraction-1" id="green">
                                            Проложить маршрут
                                        </button><br/>
                                         <button class="button button-attraction-1" id="red" onclick="">
                                            Добавить в маршрут
                                         </button>
                            </figcaption>
                        </figure>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>