<?php echo $this->top; ?>
<!-- navigation block -->
<?php echo $this->navigation; ?>
<!--/navigation block -->
<div class="container-fluid">
    <div class="span4">
        <?php echo $this->categories; ?>
        <? echo $this->event_calendar; ?>
    </div>
    <div class="span7">

        <!-- google maps block -->
        <?php echo $this->google_maps; ?>
        <!-- /google maps block -->
        <?php echo $this->marker; ?>
    </div>
    <div class="span4">
        <?php echo $this->filter; ?>
    </div>
    <?php echo $this->social; ?>
<div class="footer">
    <div class="infoot">
    </div>
</div>



